import type { Lesson, SkillPath } from "./learning-engine";

const q = (
  id: string,
  prompt: string,
  options: string[],
  answer: number,
  explanation: string,
) => ({ id, prompt, options, answer, explanation });

const lesson = (
  id: string,
  skillId: string,
  title: string,
  concept: string,
  content: string,
  example: string,
  questions: ReturnType<typeof q>[],
  minutes = 10,
): Lesson => ({
  id, skillId, title, concept, content, example, minutes, questions,
});

export const skillPaths: SkillPath[] = [
  {
    id: "python",
    title: "Python",
    description: "From zero to real programs.",
    lessons: [
      lesson("python-variables","python","Variables","Store values and reuse them.","A variable is a name bound to a value. Assignment uses =. Good variable names describe what the value represents.","x = 10\nname = \"Alex\"\nprint(x)",
        [q("q1","What does x = 10 do?",["Prints 10","Stores 10 in x","Compares x with 10"],1,"Assignment stores the value 10 in x."),q("q2","Which is a useful variable name for a user's age?",["x","age","thing"],1,"age communicates the meaning of the value.")]),
      lesson("python-strings","python","Strings","Work with text values.","Strings contain text and can be combined, indexed and processed with methods. They are written with quotes.","name = \"Alex\"\nprint(name.upper())",
        [q("q1","Which value is a string?",["42","True","\"hello\""],2,"Text inside quotes is a string."),q("q2","What does name.upper() do?",["Converts text to uppercase","Converts text to a number","Deletes the variable"],0,"upper() returns an uppercase version of the string.")]),
      lesson("python-numbers","python","Numbers","Use integers and floating-point numbers.","Python supports integer and floating-point arithmetic. Operators such as +, -, * and / combine numeric values.","price = 12.5\ncount = 2\ntotal = price * count",
        [q("q1","What is 3 * 4?",["7","12","34"],1,"Multiplication gives 12."),q("q2","Which value is a floating-point number?",["10","10.5","\"10.5\""],1,"10.5 is a numeric float; the quoted version is text.")]),
      lesson("python-conditions","python","Conditions","Choose which code runs.","if statements evaluate a condition. elif handles another condition and else handles the remaining case.","age = 18\nif age >= 18:\n    print(\"adult\")",
        [q("q1","Which keyword begins a conditional statement?",["if","for","def"],0,"Python uses if to start a conditional branch."),q("q2","What does age >= 18 produce?",["A boolean result","A list","A function"],0,"A comparison produces True or False.")]),
      lesson("python-loops","python","Loops","Repeat work efficiently.","for loops iterate over an iterable such as a list or range. while loops repeat while a condition remains true.","for i in range(3):\n    print(i)",
        [q("q1","What does range(3) produce for a for loop?",["0, 1, 2","1, 2, 3","0, 1, 2, 3"],0,"range(3) gives 0, 1 and 2."),q("q2","Which loop is commonly used to iterate through a list?",["for","if","def"],0,"for is designed to iterate over items.")]),
      lesson("python-lists","python","Lists","Store ordered collections.","Lists keep items in order and use zero-based indexing. They are mutable, so items can be changed after creation.","skills = [\"Python\", \"English\"]\nprint(skills[0])",
        [q("q1","What is skills[0]?",["English","Python","0"],1,"The first list item is Python because indexing starts at 0."),q("q2","Which method adds an item to the end of a list?",["append","push","insertEnd"],0,"append adds one item to the end.")]),
      lesson("python-functions","python","Functions","Package reusable behavior.","Functions reduce repetition and make programs easier to test. Parameters receive inputs and return sends a result back.","def add(a, b):\n    return a + b",
        [q("q1","Which keyword defines a Python function?",["func","def","return"],1,"def starts a function definition."),q("q2","What does return do?",["Sends a result back","Repeats the function","Imports a module"],0,"return exits the function and provides its result.")]),
      lesson("python-debugging","python","Errors and debugging","Use evidence to fix programs.","Read the traceback, reproduce the problem, isolate the smallest failing part, change one thing and test again. Avoid random rewrites.","try:\n    number = int(input())\nexcept ValueError:\n    print(\"Enter a number\")",
        [q("q1","What is a useful first debugging step?",["Read the traceback and reproduce it","Delete the project","Rewrite everything"],0,"The error message and reproduction give evidence about the failure."),q("q2","Which exception commonly occurs when int() receives non-numeric text?",["ValueError","NameError","KeyError"],0,"int() raises ValueError when the string cannot be converted.")]),
    ],
  },
  {
    id: "english",
    title: "English",
    description: "Grammar, vocabulary and communication.",
    lessons: [
      lesson("english-parts","english","Parts of speech","Recognize common word roles.","Nouns name things, verbs describe actions or states, adjectives describe nouns and adverbs often describe verbs or adjectives.","The careful student answered quickly.",
        [q("q1","Which word is the verb in 'She studies every day'?",["She","studies","every"],1,"studies is the action verb."),q("q2","Which word is an adjective in 'a difficult lesson'?",["a","difficult","lesson"],1,"difficult describes the noun lesson.")]),
      lesson("english-present","english","Present simple","Talk about routines and facts.","Use the present simple for routines, repeated actions and general facts. With he, she and it, affirmative verbs usually take -s or -es.","I work every day.\nShe works every day.",
        [q("q1","Choose the correct sentence.",["He work here.","He works here.","He working here."],1,"He is third-person singular, so works is required."),q("q2","Which sentence describes a routine?",["I drink tea every morning.","I drank tea yesterday.","I am drinking tea now."],0,"Every morning signals a repeated routine.")]),
      lesson("english-past","english","Past simple","Describe completed past actions.","Use the past simple for finished actions at a finished time. Regular verbs often use -ed; irregular verbs must be learned individually.","I visited London last year.",
        [q("q1","Which sentence describes a completed past action?",["I visit London every year.","I visited London last year.","I am visiting London now."],1,"visited describes a completed action at a past time."),q("q2","What is the past form of go?",["goed","went","gone"],1,"went is the simple past of go.")]),
      lesson("english-perfect","english","Present perfect","Connect past experience to the present.","Present perfect uses have or has plus a past participle. It is common for experiences, recent results and situations connected to now.","I have finished my work.",
        [q("q1","Which form is present perfect?",["have finished","finished yesterday","am finishing"],0,"have finished uses have + past participle."),q("q2","Choose the correct sentence.",["She has visited Paris.","She have visited Paris.","She has visit Paris."],0,"She takes has and the participle visited.")]),
      lesson("english-future","english","Future forms","Express plans, decisions and predictions.","Will often expresses decisions or predictions; going to commonly expresses intentions or evidence-based predictions; present continuous can describe arrangements.","I will call you later.\nI am going to study tonight.",
        [q("q1","Which sentence clearly describes a plan?",["I am going to study tonight.","I studied last night.","I study every morning."],0,"going to + verb commonly expresses an intention or plan."),q("q2","Which is a natural prediction?",["I think it will rain.","I rained yesterday.","I am rain tomorrow."],0,"will is natural for a prediction after I think.")]),
      lesson("english-context","english","Vocabulary from context","Infer meaning without translating every word.","Look at nearby words, contrast markers, examples and the situation. You can often understand the main idea without knowing every word.","The road was slippery, so the driver slowed down.",
        [q("q1","What is the best strategy for an unknown word while reading?",["Stop immediately","Use context and continue when possible","Translate every word first"],1,"Context clues often give enough information to keep reading."),q("q2","Which clue is especially useful for understanding contrast?",["however","and","number"],0,"however commonly signals a contrast between ideas.")]),
      lesson("english-speaking","english","Speaking clearly","Use complete and polite communication.","Useful speaking skills include asking for repetition, clarifying meaning and giving short direct answers. Fluency grows through repeated use.","Could you repeat that, please?",
        [q("q1","Which is a polite request for repetition?",["Repeat.","Could you repeat that, please?","You repeat now."],1,"Could you... please? is a standard polite request."),q("q2","What can you say when you do not understand?",["Could you explain that again?","I understand everything.","No words."],0,"The first phrase directly asks for clarification.")]),
      lesson("english-writing","english","Writing paragraphs","Organize one clear idea.","A strong paragraph normally has a topic sentence, supporting reasons or examples, and a closing sentence or link to the next idea.","Topic → reasons/examples → closing sentence",
        [q("q1","What usually introduces the main idea of a paragraph?",["Topic sentence","Random detail","Reference list"],0,"The topic sentence introduces the paragraph's main idea."),q("q2","What makes a paragraph easier to follow?",["Logical order","Random order","Only long sentences"],0,"Logical order creates a clear progression of ideas.")]),
    ],
  },
  {
    id: "ai",
    title: "AI",
    description: "AI concepts, prompting and practical workflows.",
    lessons: [
      lesson("ai-basics","ai","What AI is","Understand AI, machine learning and generative AI.","AI is a broad field. Machine learning uses data to learn patterns. Generative AI produces new text, images, audio, code or other content from learned patterns.","AI → machine learning → many specialized approaches",
        [q("q1","What is machine learning primarily about?",["Learning patterns from data","Only storing files","Only writing rules by hand"],0,"Machine learning uses data and algorithms to learn patterns."),q("q2","What does generative AI commonly do?",["Generate new content","Only sort folders","Only measure battery"],0,"Generative systems can produce new content such as text or images.")]),
      lesson("ai-data","ai","Training data","Understand how data affects model behavior.","Models learn from examples. Data quality, coverage and labeling can affect what patterns are learned and where errors appear.","Examples → patterns → model behavior",
        [q("q1","Why does training data quality matter?",["It can affect learned patterns","It only changes screen size","It has no effect"],0,"Training examples influence what the model learns."),q("q2","What is noisy data?",["Data containing errors or irrelevant variation","Perfectly labeled data","A computer fan"],0,"Noise is unwanted variation or error in data.")]),
      lesson("ai-prompting","ai","Prompt structure","Give an AI task, context and constraints.","A useful prompt states what you want, provides necessary context and specifies important constraints such as audience, length, format or examples.","Task + context + constraints + output format",
        [q("q1","Which prompt is more specific?",["Explain Python.","Explain Python lists to a beginner with one example and a 3-question quiz."],1,"The second prompt defines audience, topic, example and output."),q("q2","Which detail controls the response format?",["Output requirements","The user's wallpaper","Battery level"],0,"Output requirements specify how the result should be structured.")]),
      lesson("ai-examples","ai","Few-shot examples","Use examples to demonstrate a desired pattern.","A few-shot prompt includes examples of inputs and outputs. This can clarify formatting, classification and style without a long rule list.","Example input → example output → new input",
        [q("q1","What is a few-shot prompt?",["A prompt containing examples","A prompt with no task","A hardware benchmark"],0,"Few-shot prompting gives the model examples to follow."),q("q2","Why are examples useful?",["They demonstrate the expected pattern","They remove the need for a goal","They guarantee factual accuracy"],0,"Examples make the intended pattern more explicit.")]),
      lesson("ai-verification","ai","Verification","Check important claims against reliable evidence.","AI output can contain factual errors, outdated information or invented details. For important claims, verify using authoritative or primary sources.","Claim → source → comparison → conclusion",
        [q("q1","What should you do with an important factual claim?",["Verify it","Assume it is correct","Repeat it many times"],0,"Verification checks whether the claim is supported."),q("q2","Which source is generally strongest for an official API rule?",["Official documentation","A random comment","An unrelated meme"],0,"Official documentation is the primary source for API behavior.")]),
      lesson("ai-coding","ai","AI for coding","Use AI as a coding assistant, not as a substitute for testing.","A reliable coding workflow is prompt → generated code → run → inspect → test → revise. Requirements and errors should guide the next prompt.","Prompt → code → run → test → fix",
        [q("q1","What should follow AI-generated code?",["Testing and inspection","Immediate deployment without testing","Deleting requirements"],0,"Running and testing reveal whether the code actually works."),q("q2","What is useful to give an AI coding assistant?",["The exact error and relevant code","Only 'it doesn't work'","No requirements"],0,"Concrete evidence produces more actionable debugging.")]),
      lesson("ai-workflows","ai","Automation workflows","Design repeatable AI-assisted processes.","A robust workflow has a trigger, processing steps, validation and a defined output. Each step should have a clear purpose.","Trigger → process → validate → deliver",
        [q("q1","Which sequence is most robust?",["Generate only","Trigger → process → validate → deliver","Deliver before processing"],1,"Validation before delivery reduces avoidable errors."),q("q2","Why add validation?",["To catch bad outputs","To make the workflow random","To remove the goal"],0,"Validation provides a quality gate.")]),
      lesson("ai-project","ai","AI project design","Turn an idea into a measurable system.","Define the user problem, inputs, desired outputs, constraints, success criteria and validation method before adding features.","Goal + inputs + process + validation + output",
        [q("q1","What should be defined first?",["A clear goal","A random feature list","The final icon"],0,"A clear goal determines what the product should accomplish."),q("q2","What is a success criterion?",["A measurable condition for acceptable results","A color preference only","A random prompt"],0,"Success criteria make it possible to evaluate the result.")]),
    ],
  },
  {
    id: "programming",
    title: "Programming",
    description: "Logic, data, debugging, testing and projects.",
    lessons: [
      lesson("prog-algorithms","programming","Algorithms","Turn problems into ordered steps.","An algorithm is a finite procedure. Start by defining inputs and outputs, then break the task into smaller operations.","Input → process → output",
        [q("q1","What is an algorithm?",["A step-by-step procedure","Only a variable","A computer screen"],0,"An algorithm is a procedure for solving a problem."),q("q2","Why break a problem into steps?",["It reduces complexity","It makes requirements disappear","It prevents testing"],0,"Smaller steps are easier to reason about and test.")]),
      lesson("prog-logic","programming","Boolean logic","Combine true and false conditions.","Boolean logic uses values True and False. and requires both conditions; or requires at least one; not reverses a boolean.","age >= 18 and has_id",
        [q("q1","What type of value is True?",["string","boolean","list"],1,"True is a boolean value."),q("q2","What does A and B require?",["Both A and B are true","Only A is true","Neither is true"],0,"and is true only when both inputs are true.")]),
      lesson("prog-data","programming","Data structures","Choose a structure based on how data is used.","Lists preserve order, sets store unique values and dictionaries map keys to values. The right structure makes code clearer and faster to reason about.","list, set, dictionary",
        [q("q1","Which Python structure stores key-value pairs?",["list","tuple","dictionary"],2,"Dictionaries map keys to values."),q("q2","Which structure is designed for unique values?",["set","list","string"],0,"A set stores unique elements.")]),
      lesson("prog-io","programming","Input and output","Move information into and out of programs.","Input functions receive data; output functions display or return results. Keep input handling separate from core logic when possible.","name = input(\"Name: \")\nprint(name)",
        [q("q1","Which function reads text from the user in Python?",["input","print","len"],0,"input reads a line from the user."),q("q2","Which function displays text in Python?",["read","print","showText"],1,"print sends text to standard output.")]),
      lesson("prog-modules","programming","Modules","Reuse and organize code.","Modules let programs reuse functionality without putting everything in one file. Imports make dependencies explicit.","import math\nmath.sqrt(25)",
        [q("q1","Which keyword imports a module?",["use","import","include"],1,"Python uses import."),q("q2","Why use modules?",["To organize and reuse code","To remove all functions","To avoid names"],0,"Modules separate reusable functionality.")]),
      lesson("prog-debugging","programming","Debugging","Use evidence to locate defects.","A disciplined loop is reproduce → inspect → isolate → change → test. Keep changes small so you can identify what fixed or caused the behavior.","reproduce → inspect → change → test",
        [q("q1","What is a useful first step when a program fails?",["Read the error and reproduce it","Delete the project","Change unrelated code"],0,"The error and reproduction establish evidence."),q("q2","Why make one small change at a time?",["It isolates cause and effect","It makes code longer","It avoids testing"],0,"Small changes make debugging easier to reason about.")]),
      lesson("prog-testing","programming","Testing","Check expected behavior with repeatable cases.","Tests turn expectations into executable checks. Unit tests focus on small pieces; integration tests check how pieces work together.","assert add(2, 3) == 5",
        [q("q1","Why are tests useful?",["They reveal failures and regressions","They guarantee perfect software","They replace requirements"],0,"Tests catch behavior that does not match expectations."),q("q2","What does a unit test usually focus on?",["A small component","The entire internet","Only the UI color"],0,"Unit tests target a small unit of behavior.")]),
      lesson("prog-architecture","programming","Project architecture","Separate responsibilities so code can grow.","Separating UI, application logic and data reduces coupling. Clear boundaries make later changes safer and easier to test.","UI → logic → data",
        [q("q1","Why separate UI and business logic?",["To make changes easier to isolate","To make every file identical","To avoid testing"],0,"Separation of concerns reduces coupling."),q("q2","What should a good module have?",["A focused responsibility","Every feature in the app","No clear purpose"],0,"Focused modules are easier to understand and maintain.")]),
    ],
  },
];