import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Clock3, Flame, Target, Trophy } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { SkillCard } from "@/components/skill-card";
import { StatCard } from "@/components/stat-card";
import { dailySteps, skills } from "@/lib/demo-data";
import { useDemoProgress } from "@/hooks/use-demo-progress";

export const Route = createFileRoute("/dashboard")({ head:()=>({meta:[{title:"Dashboard — SkillForge"},{name:"description",content:"Your daily learning dashboard and progress."},{property:"og:title",content:"Dashboard — SkillForge"},{property:"og:description",content:"Your daily learning dashboard and progress."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: Dashboard });
function Dashboard(){ const {completed}=useDemoProgress(); const pct=Math.round(completed.length/3*100); return <AppShell title="Good morning, Alex" eyebrow="Tuesday, September 22">
  <div className="grid gap-4 sm:grid-cols-3"><StatCard label="CURRENT STREAK" value="12 days" detail="Best: 18 days" Icon={Flame}/><StatCard label="TIME THIS WEEK" value="1h 32m" detail="+18% from last week" Icon={Clock3}/><StatCard label="LESSONS DONE" value="82" detail="Top 14% of learners" Icon={Trophy}/></div>
  <section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(280px,.5fr)]"><div className="rounded-md border border-border bg-card p-5 sm:p-6"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4"><div><p className="text-xs font-bold uppercase text-primary">Today's plan · Python</p><h2 className="mt-2 text-2xl font-bold">Functions that do the work</h2><p className="mt-2 text-sm text-muted-foreground">One concept, one practice, one reflection.</p></div><span className="grid size-11 shrink-0 place-items-center rounded-md bg-accent text-accent-foreground"><Target /></span></div><div className="my-6 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all" style={{width:`${pct}%`}} /></div><b className="text-sm">{pct}%</b></div><div className="space-y-2">{dailySteps.map(step=><div key={step.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-md bg-secondary/60 p-3"><span className={`grid size-7 place-items-center rounded-full ${completed.includes(step.id)?'bg-primary text-primary-foreground':'border border-border text-muted-foreground'}`}>{completed.includes(step.id)?<Check className="size-4"/>:<span className="size-1.5 rounded-full bg-muted-foreground"/>}</span><span className="truncate text-sm font-semibold">{step.title}</span><span className="text-xs text-muted-foreground">{step.minutes}m</span></div>)}</div><Button asChild variant="forge" className="mt-5 w-full sm:w-auto"><Link to="/daily">Continue plan <ArrowRight /></Link></Button></div>
  <div className="rounded-md border border-border bg-card p-5"><p className="text-xs font-bold uppercase text-primary">Weekly goal</p><h2 className="mt-2 text-lg font-bold">5 focused sessions</h2><div className="my-6 grid grid-cols-7 gap-2">{['M','T','W','T','F','S','S'].map((day,i)=><div key={`${day}${i}`} className="text-center"><span className={`mx-auto grid size-8 place-items-center rounded-full text-xs font-bold ${i<4?'bg-primary text-primary-foreground':'bg-secondary text-muted-foreground'}`}>{i<4?<Check className="size-3"/>:day}</span><p className="mt-2 text-[10px] text-muted-foreground">{day}</p></div>)}</div><p className="text-sm leading-6 text-muted-foreground"><b className="text-foreground">One more session</b> to reach your weekly goal. Keep the chain alive.</p></div></section>
  <div className="mt-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase text-primary">Keep building</p><h2 className="mt-1 text-xl font-bold">Your skill paths</h2></div><Button asChild variant="ghost"><Link to="/skills">View all <ArrowRight /></Link></Button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{skills.map(skill=><SkillCard key={skill.id} skill={skill} active={skill.id==='python'}/>)}</div>
 </AppShell> }